import {readFile, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {sources} from '../shared/sources.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const ids = JSON.parse(await readFile(resolve(root, 'tests/index.json'), 'utf8'));
const studies = await Promise.all(ids.map(async id => ({id, ...JSON.parse(await readFile(resolve(root, 'tests', id, 'study.json'), 'utf8'))})));
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const arrow = '<span aria-hidden="true">↗</span>';
const logo = '<svg viewBox="0 0 32 36" aria-hidden="true"><path d="m16 2 13 7v17l-13 8L3 26V9Z M3 9l13 8 13-8 M16 17v17 M9 6l14 8v8l-7 4"/></svg>';
const siteUrl = 'https://ejhong.github.io/cast/';
const pageHead = (title, description, base, module, study = null) => {
  const url = new URL(study ? `tests/${study.id}/` : '', siteUrl).href;
  const preview = study || studies[0];
  const image = new URL(`assets/previews/${preview.id}.png`, siteUrl).href;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)} — CAST</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#eeeae1">
<meta property="og:title" content="${esc(title)} — CAST"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website">
<meta property="og:site_name" content="CAST — A stone-making atlas"><meta property="og:url" content="${esc(url)}"><link rel="canonical" href="${esc(url)}">
<meta property="og:image" content="${esc(image)}"><meta property="og:image:type" content="image/png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="900"><meta property="og:image:alt" content="${esc(preview.sceneDescription)}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)} — CAST"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(image)}"><meta name="twitter:image:alt" content="${esc(preview.sceneDescription)}">
<link rel="icon" href="${base}assets/icon.svg" type="image/svg+xml"><link rel="preload" href="${base}assets/fonts/newsreader-regular.ttf" as="font" type="font/ttf" crossorigin>
<link rel="stylesheet" href="${base}style.css"><script type="importmap">{"imports":{"three":"${base || './'}assets/vendor/three.module.min.js"}}</script>
<script type="module" src="${base}shared/${module}.js"></script></head>`;
};
const header = base => `<a class="skip" href="#main">Skip to content</a><header class="site-header wrap"><a class="brand" href="${base}index.html">${logo}<span>CAST<span class="brand-sub">A STONE-MAKING ATLAS</span></span></a><nav aria-label="Main navigation"><a href="${base}index.html#idea">The idea</a><a href="${base}index.html#studies">The studies <span class="nav-count">${String(studies.length).padStart(2,'0')}</span></a><a href="${base}index.html#questions">The possibilities</a><a class="research-nav" href="${sources.aletheia.url}">The research ${arrow}</a></nav></header>`;
const footer = base => `<footer class="site-footer wrap"><a class="brand" href="${base}index.html">${logo}<span>CAST</span></a><p>A visual inquiry into how stone might be made.</p><div><a href="${base}index.html#about">About the atlas</a><a href="${sources.aletheia.url}">Explore the evidence ${arrow}</a></div></footer>`;
const sourceList = keys => `<ol class="source-list">${keys.map(key => {const s = sources[key]; if (!s) throw new Error('Unknown source: '+key); return `<li><a href="${esc(s.url)}">${esc(s.title)} ${arrow}</a><span>${esc(s.author)}</span><p>${esc(s.note)}</p></li>`;}).join('')}</ol>`;
const stage = (s, base, hero = false) => `<div class="stage-shell ${hero ? 'hero-stage' : ''}" data-study="${s.id}" data-initial="${s.initial}">
  <div class="plate-heading"><span>${hero ? 'A FORM BECOMES A STONE' : `${s.number} / ${esc(s.place)}`}</span><span class="live-indicator">PROCESS STUDY</span></div>
  <div class="scene-view" id="scene-view"><img class="scene-poster" src="${base}assets/previews/${s.id}.png" width="1200" height="900" alt="${esc(s.sceneDescription)}" ${hero ? 'fetchpriority="high"' : ''}><canvas id="scene" aria-label="${esc(s.sceneDescription)}" tabindex="0"></canvas><div class="scene-hint">Drag to rotate <span>·</span> Arrow keys to orbit</div><div class="scene-fallback" hidden>Interactive 3D is unavailable here. The illustration and process steps are still available.</div></div>
  ${hero ? `<div class="hero-player"><button class="play-button" id="play" type="button"><span class="play-icon" aria-hidden="true">▶</span><span class="play-label">Watch it take shape</span></button><a href="tests/pumapunku/">Explore the H-block ${arrow}</a></div>` : `<div class="player-controls"><button class="play-button" id="play" type="button"><span class="play-icon" aria-hidden="true">▶</span><span class="play-label">Play process</span></button><label class="sr-only" for="timeline">Process timeline</label><input id="timeline" type="range" min="0" max="1000" step="1" value="${s.initial*1000}" aria-valuetext="Process stage"><output id="progress-label" for="timeline">${Math.round(s.initial*100)}%</output><button class="reset-view" id="reset-view" type="button" aria-label="Reset camera view" title="Reset camera view">⟲</button></div>`}
  </div>`;
const card = (s, i) => `<article class="study-card ${studies.length%2&&i===studies.length-1?'wide-card':''}"><a href="tests/${s.id}/" class="study-card-link"><div class="card-art"><img src="assets/previews/${s.id}.png" alt="${esc(s.sceneDescription)}" width="1200" height="900" loading="lazy"><span class="art-number">${s.number}</span><span class="art-action">Explore the process ${arrow}</span></div><div class="card-copy"><div class="eyebrow">${esc(s.place)}</div><div class="card-title"><h3>${esc(s.shortTitle)}</h3>${arrow}</div><p>${esc(s.summary)}</p><div class="tags">${s.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></div></a></article>`;
const scenarios = s => s.scenarios ? `<div class="scenario-picker"><p class="eyebrow">COMPARE THE SEQUENCE</p><div class="scenario-buttons" role="group" aria-label="Construction sequence">${s.scenarios.map((v,i)=>`<button type="button" data-scenario="${esc(v.id)}" aria-pressed="${i===0}">${esc(v.label)}</button>`).join('')}</div><p id="scenario-description" aria-live="polite">${esc(s.scenarios[0].description)}</p></div>` : '';
const caseStudy = (s,base) => {
  const c=s.caseStudy;if(!c)return '';
  const source=sources[c.source];if(!source)throw new Error('Unknown case source: '+c.source);
  const heading=`<div class="case-heading"><p class="eyebrow">${esc(c.eyebrow)}</p><h2 id="case-title">${esc(c.title)}</h2><p>${esc(c.intro)}</p></div>`;
  const metrics=c.metrics?.length?`<dl class="case-metrics">${c.metrics.map(v=>`<div><dt>${esc(v.label)}</dt><dd>${esc(v.value)}<span>${esc(v.detail)}</span></dd></div>`).join('')}</dl>`:'';
  const reading=`<div class="case-reading">${c.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}</div>`;
  const link=`<a class="text-link" href="${esc(source.url)}">${esc(c.linkLabel||'Read the primary survey')} ${arrow}</a>`;
  if(c.image){
    const im=c.image;
    return `<section class="case-study case-study-photo" aria-labelledby="case-title"><figure class="case-photo"><a href="${esc(im.creditUrl)}"><img src="${base}${esc(im.src)}" width="${im.width}" height="${im.height}" alt="${esc(im.alt)}" loading="lazy"></a><figcaption>${esc(im.caption)}<span><a href="${esc(im.creditUrl)}">${esc(im.credit)}</a> · <a href="${esc(im.licenseUrl)}">${esc(im.license)}</a></span></figcaption></figure><div class="case-photo-copy">${heading}${metrics}${reading}${link}</div></section>`;
  }
  return `<section class="case-study" aria-labelledby="case-title">${heading}${metrics}${reading}${link}</section>`;
};

const home = `${pageHead('What if stone began soft?', `${studies.length} illustrated studies of the casting hypothesis. Explore molds, polygonal walls, pyramid blocks, drainage nubs, and the Aswan quarry.`, '', 'home')}
<body class="home-page">${header('')}<main id="main">
<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="tiny-cross">+</span> ANCIENT STONE / ANOTHER POSSIBILITY</p><h1>What if stone<br>began <em>soft?</em></h1><p class="hero-deck">Before the monument, a mixture.<br>Before the sharp edge, a mold.<br>Before the mystery, a process.</p><p class="hero-intro">A visual exploration of the casting hypothesis.<br>${studies.length} ways to imagine stone taking shape.</p><a class="button" href="#studies">Explore the studies <span aria-hidden="true">↓</span></a></div>${stage(studies[0], '', true)}</section>
<div class="atlas-strip wrap"><span>${String(studies.length).padStart(2,'0')} PROCESS STUDIES</span><span>FROM THE ANDES TO THE NILE</span><span>ONE QUESTION: HOW WAS IT MADE?</span></div>
<section class="idea-section wrap" id="idea"><div><p class="eyebrow">01 / THE IDEA</p><h2>Make the shape.<br><em>Then make it stone.</em></h2></div><div class="idea-copy"><p class="large-copy">Joseph Davidovits proposed a different starting point for some ancient masonry: mineral ingredients made workable, formed, and hardened into stone.</p><p>His limestone demonstrations make the idea tangible. Could the same change in sequence help explain a tight joint, a repeated recess, or an enormous block in a confined space? <a class="inline-source" href="${sources['davidovits-formula'].url}" aria-label="Davidovits’ account of his limestone demonstration">[1]</a></p><p>The studies below bring proposed mechanisms into view. The Egyptian limestone proposal, Andean casting ideas, and Marcell Fóti’s natron hypothesis involve different materials and processes. Each has its own questions to answer.</p><a class="text-link" href="${sources.aletheia.url}">Read the “Cast, Not Carved” case ${arrow}</a></div></section>
<section class="studies-section wrap" id="studies"><div class="section-heading"><div><p class="eyebrow">02 / THE ATLAS</p><h2>Watch a possibility<br><em>take shape.</em></h2></div><p>Open a study. Play the process.<br>Turn it around. Look at what it might leave behind.</p></div><div class="study-grid">${studies.map(card).join('')}</div></section>
<section class="possibilities-band" id="questions"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">03 / WHAT CHANGES?</p><h2>A different way<br><em>through the problem.</em></h2></div><p>Making stone workable changes the construction problem. Here is what each proposed process could make easier.</p></div><div class="possibility-list">
${[
  ['01', 'An enormous load', 'Carry manageable portions; let them become one large block at the destination.', 'pyramid-blocks'],
  ['02', 'A quarry far away', 'Local ingredients could shorten the route—if they are suitable. Imported aggregate still needs transport.', 'pyramid-blocks'],
  ['03', 'An opening too narrow', 'Bring in baskets and mold panels, then make the vessel inside. Compare installation before roofing.', 'narrow-doorway'],
  ['04', 'A joint that barely shows', 'Let workable material take the shape of its neighbors, then test how much the joint opens on curing.', 'inca-walls'],
  ['05', 'Precision in hard stone', 'Make the difficult geometry in a mold and transfer it to material that is still workable.', 'pumapunku'],
  ['06', 'A nub on the surface', 'A cloth-covered drain could retain a bulge of material as water escapes.', 'drainage-nubs'],
  ['07', 'A field of scoop marks', 'Repeated surface treatment and removal might leave a repeatable pattern of depressions.', 'aswan-quarry'],
  ['08', 'A rope-like groove', 'A soft surface can take an impression of the rope, including the pattern of its strands.', 'rope-impressions'],
  ['09', 'A seam across the stone', 'Material entering a gap between mold boards can leave a raised fin when the boards are removed.', 'mold-seams'],
  ['10', 'A block that turns a corner', 'Wrap a hide around a supported angle, then let a continuous block form in the L-shaped cavity.', 'bent-corners']
].map(([n,title,copy,id])=>`<a class="possibility-row" href="tests/${id}/#possibilities"><span class="row-number">${n}</span><h3>${title}</h3><p>${copy}</p>${arrow}</a>`).join('')}
</div><p class="band-note">These are proposed explanations. A useful mechanism must also fit the material, the marks, and the archaeological context.</p></div></section>
<section class="logistics-section wrap" id="small-loads"><div><p class="eyebrow">04 / A SMALL THOUGHT EXPERIMENT</p><h2>The same mass.<br><em>A different journey.</em></h2><p>Making a block in place could turn one difficult lift into many smaller deliveries. Try changing the block and the load.</p><a class="text-link" href="tests/pyramid-blocks/">See the process ${arrow}</a></div><div class="logistics-widget"><div class="load-diagram" aria-hidden="true"><svg viewBox="0 0 500 145"><defs><pattern id="load-grain" width="6" height="6" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#eeeae1" opacity=".3"/></pattern></defs><path d="m45 25 100-15 53 29-102 20Z" fill="#bab19e"/><path d="M45 25v78l51 31V59Z" fill="#6c7265"/><path d="m96 59 102-20v77l-102 18Z" fill="#a9ad97"/><path d="m96 59 102-20v77l-102 18Z" fill="url(#load-grain)"/><path d="M239 75h61m-9-8 9 8-9 8" stroke="#8e7760" stroke-width="1.5" fill="none"/><g fill="#a99f87" stroke="#7e7462">${Array.from({length:12},(_,i)=>{const x=340+i%4*32, y=36+Math.floor(i/4)*31;return `<path d="m${x} ${y} 21-4 8 5-21 5Z"/><path d="m${x} ${y} 8 6v17l-8-5Z"/><path d="m${x+8} ${y+6} 21-5v17l-21 5Z"/>`;}).join('')}</g></svg></div><div class="load-result"><div><output id="block-output" for="block-mass">12</output><span>TONNE BLOCK</span></div><span class="load-equals">→</span><div><output id="trips-output" for="block-mass load-mass">480</output><span>SMALL LOADS</span></div></div><label class="slider-label" for="block-mass">Finished block <output id="mass-label" for="block-mass">12 tonnes</output></label><input id="block-mass" type="range" min="1" max="40" step="1" value="12"><label class="slider-label" for="load-mass">Material per load <output id="load-label" for="load-mass">25 kg</output></label><input id="load-mass" type="range" min="10" max="40" step="1" value="25"><p class="widget-note">Illustrative arithmetic: finished mass ÷ load. Added process water, material losses, route, lifting height, and return trips are not included.</p></div></section>
<section class="about-section wrap" id="about"><div><p class="eyebrow">AN ATLAS THAT CAN GROW</p><h2>One feature.<br>One process.<br><em>A closer look.</em></h2></div><div class="about-copy"><p>Every new study starts with something observable: a rope-like groove, a joint, a scoop, a surface impression. Then comes a proposed mechanism, an animation, and a test that could tell us whether it fits.</p><p>These studies are conceptual reconstructions. Their shapes and timing are illustrative; they are not archaeological scans or validated physical simulations. Conventional quarrying and stoneworking remain essential comparisons.</p><div class="next-studies"><span class="eyebrow">NEXT ON THE WORKBENCH</span><p>Quarry-to-site journeys <span>·</span> Batch bonding <span>·</span> A recipe under a microscope</p></div><a class="text-link" href="${sources.aletheia.url}">Follow the evidence at Aletheia ${arrow}</a></div></section>
</main>${footer('')}<noscript><p class="noscript-note wrap">The illustrations and all study text work without JavaScript. Enable it to play the 3D processes and use the load calculator.</p></noscript></body></html>`;
await writeFile(resolve(root, 'index.html'), home);

for (let i=0; i<studies.length; i++) {
  const s=studies[i], next=studies[(i+1)%studies.length], base='../../';
  const html=`${pageHead(s.title, s.summary, base, 'player', s)}
<body class="study-page" data-study="${s.id}">${header(base)}<main id="main" class="wrap">
<a class="back-link" href="${base}index.html#studies">← Back to the atlas</a>
<section class="study-intro"><div><p class="eyebrow">STUDY ${s.number} / ${esc(s.place)}</p><h1>${esc(s.title)}</h1></div><div><p class="study-subtitle">${esc(s.subtitle)}</p><div class="tags">${s.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></div></section>
<section class="experiment" aria-label="Interactive process study"><div class="experiment-main">${scenarios(s)}${stage(s, base)}<div class="stage-options"><label class="check-control"><input id="scene-option" type="checkbox" ${s.control.checked!==false?'checked':''}><span>${esc(s.control.label)}</span></label><span>ILLUSTRATED HYPOTHESIS · NOT TO SCALE</span></div></div><div class="process-panel"><p class="eyebrow">FOLLOW THE MAKING</p><div class="process-steps" aria-label="Choose a process stage">${s.steps.map((step,j)=>`<button type="button" class="step-button" data-step="${j}" aria-pressed="false"><span>${String(j+1).padStart(2,'0')}</span><span class="step-name">${esc(step.name)}</span><span class="step-dot" aria-hidden="true"></span></button>`).join('')}</div><div class="step-detail" aria-live="polite" aria-atomic="true"><p class="eyebrow" id="step-number">STAGE 01</p><h2 id="step-title">${esc(s.steps[0].title)}</h2><p id="step-text">${esc(s.steps[0].text)}</p></div></div></section>
<p class="model-note"><span>ABOUT THIS MODEL</span>${esc(s.modelNote)}</p>
${caseStudy(s,base)}
<section class="issues-section" id="possibilities"><div class="section-heading"><div><p class="eyebrow">THE EXPLANATORY IDEA</p><h2>What could this<br><em>make easier?</em></h2></div><p>${esc(s.summary)}</p></div><div class="issue-grid">${s.issues.map((issue,j)=>`<article><span class="issue-number">${String(j+1).padStart(2,'0')}</span><h3>${esc(issue.title)}</h3><p>${esc(issue.mechanism)}</p><p class="remaining"><span>Still to explain</span>${esc(issue.remaining)}</p></article>`).join('')}</div></section>
<section class="evidence-section"><div><p class="eyebrow">FROM POSSIBILITY TO EVIDENCE</p><h2>How would<br><em>we tell?</em></h2></div><div class="evidence-copy"><h3>The proposal</h3><p>${esc(s.hypothesis)}</p><h3>The comparison</h3><p>${esc(s.alternative)}</p><div class="test-proposal"><span class="eyebrow">A USEFUL PHYSICAL TEST</span><p>${esc(s.test)}</p></div></div></section>
<section class="sources-section" id="sources"><details><summary><span>Sources & further reading</span><span class="source-count">${s.sources.length} REFERENCES <span aria-hidden="true">+</span></span></summary>${sourceList(s.sources)}</details></section>
<a class="next-study" href="../${next.id}/"><div><span class="eyebrow">NEXT / STUDY ${next.number}</span><h2>${esc(next.shortTitle)}</h2></div>${arrow}</a>
</main>${footer(base)}<noscript><div class="wrap noscript-note"><p>Enable JavaScript to play or rotate the model. The process in order:</p><ol>${s.steps.map(step=>`<li><strong>${esc(step.name)}.</strong> ${esc(step.text)}</li>`).join('')}</ol></div></noscript></body></html>`;
  await writeFile(resolve(root, 'tests', s.id, 'index.html'), html);
}
console.log(`Built the atlas and ${studies.length} study pages.`);
